spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: utf-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/tanwb?useUnicode=true
    username: root
    password: Root.123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 53020
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path:  /uaa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:53000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: ['text/xml', 'application/xml', 'application/json']
      min-request-size: 2048
    response:
      enabled: true