spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true

server:
  port: 53010

zuul:
  retryable: true
  add-host-header: true
  routes:
    uaa-service:
      stripPrefix: false
      path: /uaa/**
    order-service:
      stripPrefix: false
      path: /order/**
  ignored-services: '*'
  sensitive-headers: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:53000/eureka/

logging:
  level:
    root: info
  org:
    springframework: info

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: ['text/xml', 'application/xml', 'application/json']
      min-request-size: 2048
    response:
      enabled: true